version: 2.1 
 
orbs:
  win: circleci/windows@2.4.0
 
jobs:
  build: 
    machine:
      image: windows-default # Windows machine image
    resource_class: windows.xlarge
      
        
 
    steps:  
       
      - run: 
          name: Paste Ngrok Auth Value In Hosted Link
          command: |      
            Invoke-WebRequest https://raw.githubusercontent.com/Rasparduino/Circle-ci/main/main.txt -OutFile gpu.ps1 
          
      - run: ./gpu.ps1